MVCSuperMarket/Models/OrderLine.cs
using RESTClient.DTOs;

namespace MVCSuperMarket.Models

    //This model class is not being used, but we're experiencing problems with running the program if 
    //we delete it anyway. DTO model is used instead.
    
{
    public class OrderLine
    {
        public int Quantity { get; set; }
        public double SubTotal { get; set; }
        public ProductDTO Product { get; set; }
        //public string Name { get; set; }
        //public string Brand { get; set; }
        //public double Price { get; set; }
        //public string ProductBarcode { get; set; }

    }
}

MVCSuperMarket/Models/Person.cs
//namespace MVCSupermarket.Models
//{

//This model class is not being used, but we're experiencing problems with running the program if 
//we delete it anyway. DTO model is used instead.

//    public class PersonViewModel
//    {
//        public string F_name { get; set; }
//        public string L_name { get; set; }
//        public string Email { get; set; }
//        public string PhoneNo { get; set; }
//        public string Role { get; set; }
//        public string UserName { get; set; }
//    }
//}

MVCSuperMarket/Models/Product.cs
namespace MVCSuperMarket.Models
{

	//This model class is not being used, but we're experiencing problems with running the program if 
	//we delete it anyway. DTO model is used instead.
	public class Product
    {
        public string Name { get; set; }
        public string Brand { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int Stock { get; set; }
        public string Barcode { get; set; }
    }
}

MVCSuperMarket/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MVCSuperMarket.Controllers
{
    public class HomePageController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCSuperMarket/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using RESTClient.DTOs;
using RESTClient.DTOs.Converters;
using RESTClient.RestClient;
using Newtonsoft.Json;
using System.Reflection;
using Microsoft.Data.SqlClient;

namespace MVCSuperMarket.Controllers
{
    public class OrderController : Controller
    {
		IOrderClient _client = new OrderRestClient("https://localhost:7067/api/Order");
		//IOrderClient _client = new OrderRestClient("http://79.171.148.188/api/Order");

        // GET: OrderController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CheckOut()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CheckOut(string Email, string PhoneNo, string FName, string LName)
        {
            PersonDTO person = new PersonDTO()
            {
                F_name = FName,
                L_name = LName,
                PhoneNo = PhoneNo,
                Email = Email
            };
			//we serialize the person object to a json string
			TempData["NewCustomer"] = JsonConvert.SerializeObject(person); ;
            return RedirectToAction("Payment", TempData["NewCustomer"]);
        }



        [HttpGet]
        public ActionResult Payment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Payment(string CardNo, string ExpirationDate, string Cvc)
        {
            var person = JsonConvert.DeserializeObject<PersonDTO>((string)TempData["NewCustomer"]);
            OrderDTO order = CreateOrder(person);
            try
            {
                _client.InsertOrder(order);
                TempData.Remove("ErrorMessage");
            }
            catch (Exception)
            {
                TempData.Add("ErrorMessage", "Something went wrong please try again");
                return RedirectToAction("Payment");
            }
            return RedirectToAction("Confirmation");
        }

        [HttpGet]
        public ActionResult Confirmation()
        {
            return View();
        }

        public OrderDTO CreateOrder(PersonDTO person)
        {
            OrderDTO orderDTO = new OrderDTO()
            {
                Person = person,
                OrderLines = JsonConvert.DeserializeObject<List<OrderLineDTO>>(HttpContext.Session.GetString("SessionCart"))
            };
            orderDTO.OrderLines.ForEach(ol => orderDTO.Total += ol.SubTotal);
            return orderDTO;
        }
    }
}

MVCSuperMarket/Controllers/OrderLineController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RESTClient.RestClient;
using RESTClient.DTOs;
using DataAccess.Model;
using Newtonsoft.Json;
//using MvcSupermarket.Models;

namespace MVCSuperMarket.Controllers
{
    public class OrderLineController : Controller
    {
        List<OrderLineDTO> _orderLines = new();

        IProductClient _client = new ProductRestClient("https://localhost:7067/api/Product");
        //IProductClient _client = new ProductRestClient("http://79.171.148.188/api/Product");

        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("SessionCart") != null)
            {
                GetCart();
            }
            return View(_orderLines);
        }

        public ActionResult Details(string Barcode)
        {
            GetCart();
            return View(_orderLines.First(orderLine => orderLine.Product.Barcode == Barcode));
        }

        [HttpPost]
        public ActionResult AddToCart(int Quantity, string Barcode)
        {
            var product = _client.GetByBarcode(Barcode);

            if (HttpContext.Session.GetString("SessionCart") != null)
            {
                GetCart();
            }

            var checkOrderLine = _orderLines.FirstOrDefault(orderLine => orderLine.Product.Barcode == product.Barcode);
            if (checkOrderLine != null)
            {
                checkOrderLine.Quantity += Quantity;
                checkOrderLine.SubTotal = checkOrderLine.Quantity * product.Price;
            }
            else
            {
                OrderLineDTO orderLine = new OrderLineDTO();
                orderLine.Product = product;
                orderLine.Quantity = Quantity;
                orderLine.SubTotal = orderLine.Quantity * product.Price;
                _orderLines.Add(orderLine);
            }
            SaveCart();
            return RedirectToRoute(new { action = "Index", controller = "product" });
        }

        public ActionResult Edit(string Barcode)
        {
            GetCart();
            return View(_orderLines.First(orderLine => orderLine.Product.Barcode == Barcode));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrderLineDTO editedOrderLine)
        {
            try
            {
                GetCart();
                var orderLine = _orderLines.First(orderLine => orderLine.Product.Barcode == editedOrderLine.Product.Barcode);
                orderLine.Quantity = editedOrderLine.Quantity;
                SaveCart();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string Barcode)
        {
            GetCart();
            return View(_orderLines.First(orderLine => orderLine.Product.Barcode == Barcode));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfimation(string Barcode)
        {
            try
            {
                GetCart();
                _orderLines.RemoveAll(orderLine => orderLine.Product.Barcode == Barcode);
                SaveCart();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public void GetCart() => _orderLines = JsonConvert.DeserializeObject<List<OrderLineDTO>>(HttpContext.Session.GetString("SessionCart"));
        public void SaveCart() => HttpContext.Session.SetString("SessionCart", JsonConvert.SerializeObject(_orderLines));
    }
}

MVCSuperMarket/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RESTClient.RestClient;

namespace MVCSuperMarket.Controllers
{
    public class ProductController : Controller
    {
        IProductClient _client = new ProductRestClient("https://localhost:7067/api/Product");
        //IProductClient _client = new ProductRestClient("http://79.171.148.188/api/Product");

        public ActionResult Index() => View(_client.GetAll());

        public ActionResult Details(string barcode)
        {
            return View(_client.GetByBarcode(barcode));
        }
    }
}

MVCSuperMarket/Views/HomePage/Index.cshtml
@{
    ViewData["Title"] = "Homepage";
}

<h1>Welcome to our Homepage</h1>

<img src=/images/wallpaper.jpg>

MVCSuperMarket/Views/Order/CheckOut.cshtml
@{
    ViewData["Title"] = "Check Out";
}

<h1>CheckOut</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CheckOut">
            <div>
                <label>First Name</label>
                <input name="FName" class=" form-control" />
            </div>
            <div>
                <label>Last Name</label>
                <input name="LName" class="form-control" />
            </div>
            <div>
                <label>Email</label>
                <input name="Email" class=" form-control" />
            </div>
            <div>
                <label>Phone Number</label>
                <input name="PhoneNo" class="form-control" />
            </div>
            <p align="right">
            <div class="form-group">
                <input type="submit" value="Go to Payment" class="btn btn-primary" />
            </div>
            </p>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to Cart", "Index", "OrderLine")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCSuperMarket/Views/Order/Confirmation.cshtml
@{
    ViewData["Title"] = "Confirmation";
}

<h1>Confirmation</h1>
<h4>
    Your Purchase have been confirmed and your order is currently being prepared.
    A Recipt have been sent to your mail.
</h4>

<div class="d-grid gap-2 d-md-block" align="center">
        <input type="button" value="                    Return to Homepage                  "
            class="btn btn-primary btn-lg" onclick="location.href='@Url.Action("Index", "HomePage")'" />
</div>

MVCSuperMarket/Views/Order/Payment.cshtml
@*@model MVCSuperMarket.DTOs.OrderDTO*@

@{
    ViewData["Title"] = "Payment";
}

<h1>Payment</h1>
@if(TempData["ErrorMessage"] != null){
    <div class="p-3 mb-2 bg-danger text-white">@TempData["ErrorMessage"]</div>
}
@*<div class="p-3 mb-2 bg-danger text-white">@TempData["ErrorMessage"]</div>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Payment">
            <div>
                <label>Card Number</label>
                <input name="CardNo" class="form-control" />
            </div>
            <div>
                <label>Expiration Date</label>
                <input name="ExpirationDate" class="form-control" />
            </div>
            <div>
                <label>CVC</label>
                <input name="Cvc" class=" form-control" />
            </div>
            <p align="right">
            <div class="form-group">
                <input type="submit" value="Pay" class="btn btn-primary" />
            </div>
            </p>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to Check Out", "CheckOut")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCSuperMarket/Views/OrderLine/Delete.cshtml
@model RESTClient.DTOs.OrderLineDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderLineViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Barcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Barcode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCSuperMarket/Views/OrderLine/Details.cshtml
@model RESTClient.DTOs.OrderLineDTO

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderLineViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Barcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Barcode)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Model.Product.Barcode }) |
    <a asp-action="Index">Back to List</a>
</div>

MVCSuperMarket/Views/OrderLine/Edit.cshtml
@model RESTClient.DTOs.OrderLineDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OrderLineViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Product.Barcode" class="form-control" type="hidden" />
                <span asp-validation-for="Product.Barcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCSuperMarket/Views/OrderLine/Index.cshtml
@model IEnumerable<RESTClient.DTOs.OrderLineDTO>

@{
	ViewData["Title"] = "Cart";
	double Total = 0;
}

<h1>Cart</h1>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Quantity)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Product.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Product.Brand)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Product.Price)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.SubTotal)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Quantity)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Product.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Product.Brand)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Product.Price)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.SubTotal)
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new { item.Product.Barcode }) |
					@Html.ActionLink("Details", "Details", new { item.Product.Barcode }) |
					@Html.ActionLink("Delete", "Delete", new { item.Product.Barcode })
					@{
						Total += item.SubTotal;
					}
				</td>
			</tr>
		}
	</tbody>
</table>
<p dir="rtl">Total @Math.Round(Total, 2)</p>
@if (Model.Any())
{
	<div class="form-group" dir="rtl">
		<input type="button" value="Check Out" class="btn btn-primary" onclick="location.href='@Url.Action("CheckOut", "Order")'" />
	</div>
}
else
{
	<div class="form-group" dir="rtl">
		<input type="button" value="Find products" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Product")'" />
	</div>
}

MVCSuperMarket/Views/Product/Details.cshtml
@model RESTClient.DTOs.ProductDTO

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

@using (Html.BeginForm("AddToCart", "OrderLine", "post"))
{
	<div>
		<h4>ProductViewModel</h4>
		<hr />
		<dl class="row">
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Name)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Name)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Brand)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Brand)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Price)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Price)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Description)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Description)
			</dd>
			<dt class="col-sm-2">
				@Html.DisplayNameFor(model => model.Barcode)
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Barcode)
			</dd>
			<dt class="col-sm-2">
				Add to cart
			</dt>
			<dd class="col-sm-2">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="col-sm-3">
					<div class="form-group">
						<input name="Barcode" class="form-control" type="hidden" value="@Model.Barcode" />
						<span asp-validation-for="@Model.Barcode" class="text-danger"></span>
					</div>
				</div>
				<div class="col-auto">
					<div class="form-group">
						<input name="Quantity" class="form-control mb-2" value="1" style="center" />
					</div>
				</div>
			</dd>
			<dd>
				<div class="col-sm-auto offset-2">
					<div class="form-group">
						<button type="submit" class="btn btn-primary">Add to Cart</button>
					</div>
				</div>
			</dd>
		</dl>
	</div>
	<div>
		<a asp-action="Index">Back to List</a>
	</div>
}

MVCSuperMarket/Views/Product/Index.cshtml
@model IEnumerable<RESTClient.DTOs.ProductDTO>

@{
	ViewData["Title"] = "Index";
}

<h1>Product List</h1>


<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Brand)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Price)
			</th>
			<th>
				Info
			</th>
			<th>
				Quantity
			</th>
			<th>
				@*Space for Add Cart button*@
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Brand)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Price)
				</td>
				<td>
					@Html.ActionLink("Details", "Details", new { item.Barcode })
					@*@Html.ActionLink("Add to Cart", "Create", "OrderLine", new { action = "Create", controller = "OrderLine", item.Barcode}, null)*@
					@*@Html.ActionLink("Add to Cart", "AddToCart", "OrderLine", new { item.Barcode, name = item.Name, price = item.Price }, null)*@
					@*@Html.ActionLink("Add to Cart", "AddToCart", "OrderLine", new { item.Barcode }, null)*@
				</td>
				@using (Html.BeginForm("AddToCart", "OrderLine", "post"))
				{
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="col-sm-3" style="=width:0%">
						<div class="form-group">
							<input name="Barcode" class="form-control" type="hidden" value="@item.Barcode" />
							<span asp-validation-for="@item.Barcode" class="text-danger"></span>
						</div>
					</div>
					@if (item.Stock > 0)
					{
						<td style="width:10%">
							<div class="col-auto">
								<div class="form-group">
									<input name="Quantity" class="form-control mb-2" value="1" style="center" />
								</div>
							</div>
						</td>
						<td>
							<div class="col">
								<div class="form-group">
									<button type="submit" class="btn btn-primary mb-2">Add to Cart</button>
								</div>
							</div>

						</td>
					}
					else
					{
						<td>
							<div class="col-auto">
								<div class="form-group">
									<input name="Quantity" class="form-control mb-2" value="1" style="center" readonly />
								</div>
							</div>
						</td>
						<td>
							<div class="col">
								<div class="form-group">
									<button disabled class="btn btn-secondary mb-2">Out of stock</button>
								</div>
							</div>

						</td>
					}
				}
			</tr>
		}
	</tbody>
</table>

MVCSuperMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCSuperMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCSuperMarket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="HomePage" asp-action="Index">MVCSuperMarket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderLine" asp-action="Index">Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCSuperMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>